name: Check
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cargo-clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Clippy
        run: cargo clippy --all -- -D warnings

  cargo-test:
    name: Cargo test std
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Test
        run: cargo test

  check-wasm32:
    name: Cargo test wasm32
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Check wasm32
        run: cargo check --target wasm32-unknown-unknown
